apiVersion: apps/v1
kind: Deployment
metadata:
  name: claclostdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claclo-student
  template:
    metadata:
      labels:
        app: claclo-student
    spec:
      containers:
        - name: claclo-student
          image: us-central1-docker.pkg.dev/comp7033/claclo-student/claclo-student
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: claclo-student-service
spec:
  selector:
    app: claclo-student
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
